# Generated by Django 6.0.3 on 2026-03-10 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=100, unique=True)),
                ('case_title', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('property', 'Property'), ('labour', 'Labour'), ('commercial', 'Commercial'), ('constitutional', 'Constitutional'), ('other', 'Other')], default='civil', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('court_name', models.CharField(max_length=255)),
                ('court_city', models.CharField(blank=True, max_length=100)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('last_hearing_date', models.DateField(blank=True, null=True)),
                ('last_verdict', models.TextField(blank=True)),
                ('final_verdict', models.TextField(blank=True)),
                ('case_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('adjourned', 'Adjourned'), ('judgement_reserved', 'Judgement Reserved'), ('closed', 'Closed'), ('disposed', 'Disposed')], default='ongoing', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('is_visible_to_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to=settings.AUTH_USER_MODEL)),
                ('client_advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advocate_cases', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_cases', to=settings.AUTH_USER_MODEL)),
                ('opposition_advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposition_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HearingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('next_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_notes', to='cases.case')),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
    ]
